# Generated by Django 4.1.4 on 2023-01-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transactionId", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("totalAmount", models.FloatField()),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("budget", models.FloatField(blank=True, null=True)),
                ("expenditure", models.FloatField(blank=True, null=True)),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True, related_name="friend", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("logId", models.AutoField(primary_key=True, serialize=False)),
                ("payee", models.CharField(max_length=100)),
                ("payers", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                (
                    "transactionId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money_tracker.transaction",
                    ),
                ),
            ],
        ),
    ]
